### ISSUE TITLE
v0.2.x loses events on both unix socket and TCP

### ISSUE THREAD

**Issue by SuperFunks** [dnstap/golang-dnstap#34] opened 2020-09-10 14:49 UTC
Hi there,

So I've been using DNSTAP on Debian stretch for 2 years now and have been pretty happy with it - but i saw that json output was added in version v0.2.x so i decided i would upgrade.

Unfortunately i do see a lot of lost events when using this new version of DNSTAP - and I've done some extensive testing to figure out whats going on:

Resperf(8999 queries over 60 seconds) ---> CoreDNS(DNSTAP) --- TCP ---> DNSTAPv1:  8999 CQ events received.
Resperf(8999 queries over 60 seconds) ---> CoreDNS(DNSTAP) --- TCP ---> DNSTAPv2:  3223 CQ events received.
Resperf(8999 queries over 60 seconds) ---> CoreDNS(DNSTAP) --- SOCKET ---> DNSTAPv1:  8999 CQ events received.
Resperf(8999 queries over 60 seconds) ---> CoreDNS(DNSTAP) --- SOCKET ---> DNSTAPv2:  3324 CQ events received.

If i put the rate to about 10 queries pr. second DNSTAPv2 does seem to be able to keep up.

I find it hard to believe this hasn't been caught before - but nevertheless its what im facing right now.

I'm willing to spend time debugging and troubleshooting anytime you like.

**Comment by cmikk** [comment] 2020-09-10 19:08
Greetings, and thank you for reporting this.

To narrow down the bottleneck, does this message loss occur with the newer JSON output format only, or does it also occur with quiet text format or writing binary dnstap data to files?

**Comment by SuperFunks** [comment] 2020-09-10 19:43
Hi there - no problem :)

I have tested all four scenarios with binary, basic, json and yaml - all with almost the exact same loss.

0% loss on DNSTAPv1
~64% loss on DNSTAPv2

So to the question if the loss might happen in the json output module, i would say no.

**Comment by pforemski** [comment] 2020-09-11 16:04
Hi, and thank you for your report!

Could you share detailed version information on your:
- Golang compiler used to build dnstap (btw, did you use the v0.2.0 tag or v0.2.1?)
- farsightsec/golang-framestream
- golang/protobuf
- miekg/dns
- CoreDNS
- resperf (dnsperf)

**Comment by SuperFunks** [comment] 2020-09-12 06:37
Hi there,

- Golang compiler: https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
- Build version of DNSTAP was v0.2.1

~/go/src/github.com/dnstap/golang-dnstap/dnstap# go get
go: downloading github.com/farsightsec/golang-framestream v0.2.0
go: downloading github.com/miekg/dns v1.1.31
go: downloading github.com/golang/protobuf v1.4.2
go: downloading google.golang.org/protobuf v1.23.0
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: downloading golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe
go: downloading golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550

So i guess its using 2 versions of protobuf?

CoreDNS version: 1.7.0 
Resperf version: DNS Resolution Performance Testing Tool - Nominum Version 2.1.0.0

I just did a clean compile of all components - and tested once again:

**Additional information:**

**OS Release:**
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"

**Kernel version:**
uname -r
4.9.0-11-amd64

**Binary run command:**
/root/go/src/github.com/dnstap/golang-dnstap/dnstap/dnstap -j -l 127.0.0.1:6000 > /tmp/out.log

**Refperf command:**
resperf-report -s <ip> -d /home/dnsperf/queryfile -c 60 -m 100 -r 10

**Resperf results:**
Statistics:
  Queries sent:         6499
  Queries completed:    6499
  Queries lost:         0

![image](https://user-images.githubusercontent.com/20201219/92989243-2b4d8980-f4d3-11ea-89fd-3bb8ec442fca.png)

**Client Query Counts in out.log:**
cat /tmp/out.log | grep CLIENT_QUERY | wc -l
1899

I expect to see 6499 Query events in the output file - but see 1899 - meaning ~70% loss of events. :(

Hope this makes it easier for you to reproduce and debug.

**Comment by SuperFunks** [comment] 2020-09-12 07:12
Looking through the code - it seems like the there are multiple cases that flushes the buffer to write - so i decided to track on the output how the increments happen - with some interesting results:

while true; do cat /tmp/out.log | grep CLIENT_QUERY | wc -l; sleep 0.2; done

Looking at the results what i see is that the 1 second flush is always the one triggered - and knowing that Resperf is sending at a constant rate - i would expect the increment count to be solid throughout the test - but they are not!

Removing the rampup from the data this is the span of the increments every second: 17-35 - while of cause it should be 100.





Count | Increment
-- | --
1 | 1
1 | 0
1 | 0
1 | 0
1 | 0
10 | 9
10 | 0
10 | 0
10 | 0
10 | 0
26 | 16
26 | 0
26 | 0
26 | 0
26 | 0
43 | 17
43 | 0
43 | 0
43 | 0
43 | 0
60 | 17
60 | 0
60 | 0
60 | 0
60 | 0
77 | 17
77 | 0
77 | 0
77 | 0
77 | 0
111 | 34
111 | 0
111 | 0
111 | 0
111 | 0
130 | 19
130 | 0
130 | 0
130 | 0
147 | 17
147 | 0
147 | 0
147 | 0
147 | 0
164 | 17
164 | 0
164 | 0
164 | 0
164 | 0
198 | 34
198 | 0
198 | 0
198 | 0
198 | 0
232 | 34
232 | 0
232 | 0
232 | 0
232 | 0
266 | 34
266 | 0
266 | 0
266 | 0
266 | 0
300 | 34
300 | 0
300 | 0
300 | 0
300 | 0
334 | 34
334 | 0
334 | 0
334 | 0
334 | 0
366 | 32
366 | 0
366 | 0
366 | 0
366 | 0
400 | 34
400 | 0
400 | 0
400 | 0
400 | 0
432 | 32
432 | 0
432 | 0
432 | 0
432 | 0
466 | 34
466 | 0
466 | 0
466 | 0
466 | 0
498 | 32
498 | 0
498 | 0
498 | 0
532 | 34
532 | 0
532 | 0
532 | 0
532 | 0
549 | 17
549 | 0
549 | 0
549 | 0
549 | 0
566 | 17
566 | 0
566 | 0
566 | 0
566 | 0
583 | 17
583 | 0
583 | 0
583 | 0
583 | 0
618 | 35
618 | 0
618 | 0
618 | 0
618 | 0
650 | 32
650 | 0
650 | 0
650 | 0
650 | 0
681 | 31
681 | 0
681 | 0
681 | 0
681 | 0
714 | 33
714 | 0
714 | 0
714 | 0
714 | 0
731 | 17
731 | 0
731 | 0
731 | 0
731 | 0
748 | 17
748 | 0
748 | 0
748 | 0
765 | 17
765 | 0
765 | 0
765 | 0
765 | 0
798 | 33
798 | 0
798 | 0
798 | 0
798 | 0
832 | 34
832 | 0
832 | 0
832 | 0
832 | 0
867 | 35
867 | 0
867 | 0
867 | 0
867 | 0
884 | 17
884 | 0
884 | 0
884 | 0
884 | 0
903 | 19
903 | 0
903 | 0
903 | 0
903 | 0
937 | 34
937 | 0
937 | 0
937 | 0
937 | 0
956 | 19
956 | 0
956 | 0
956 | 0
956 | 0
990 | 34
990 | 0
990 | 0
990 | 0
1024 | 34
1024 | 0
1024 | 0
1024 | 0
1024 | 0
1058 | 34
1058 | 0
1058 | 0
1058 | 0
1058 | 0
1092 | 34
1092 | 0
1092 | 0
1092 | 0
1092 | 0
1126 | 34
1126 | 0
1126 | 0
1126 | 0
1126 | 0
1143 | 17
1143 | 0
1143 | 0
1143 | 0
1143 | 0
1177 | 34
1177 | 0
1177 | 0
1177 | 0
1177 | 0
1208 | 31
1208 | 0
1208 | 0
1208 | 0
1208 | 0
1225 | 17
1225 | 0
1225 | 0
1225 | 0
1225 | 0
1259 | 34
1259 | 0
1259 | 0
1259 | 0
1293 | 34
1293 | 0
1293 | 0
1293 | 0
1293 | 0
1327 | 34
1327 | 0
1327 | 0
1327 | 0
1327 | 0
1361 | 34
1361 | 0
1361 | 0
1361 | 0
1361 | 0
1395 | 34
1395 | 0
1395 | 0
1395 | 0
1395 | 0
1414 | 19
1414 | 0
1414 | 0
1414 | 0
1414 | 0
1448 | 34
1448 | 0
1448 | 0
1448 | 0
1448 | 0
1482 | 34
1482 | 0
1482 | 0
1482 | 0
1508 | 26
1508 | 0
1508 | 0
1508 | 0
1508 | 0
1541 | 33
1541 | 0
1541 | 0
1541 | 0
1541 | 0
1573 | 32
1573 | 0
1573 | 0
1573 | 0
1573 | 0
1607 | 34
1607 | 0
1607 | 0
1607 | 0
1607 | 0
1640 | 33
1640 | 0
1640 | 0
1640 | 0
1640 | 0
1674 | 34
1674 | 0
1674 | 0
1674 | 0
1685 | 11
1691 | 6
1691 | 0
1691 | 0
1691 | 0
1724 | 33
1724 | 0
1724 | 0
1724 | 0
1724 | 0
1756 | 32
1756 | 0
1756 | 0
1756 | 0
1756 | 0
1778 | 22
1778 | 0
1778 | 0
1778 | 0
1778 | 0
1812 | 34
1812 | 0
1812 | 0
1812 | 0
1812 | 0
1846 | 34
1846 | 0
1846 | 0
1846 | 0
1846 | 0
1880 | 34
1880 | 0
1880 | 0
1880 | 0
1913 | 33
1913 | 0
1913 | 0
1913 | 0
1913 | 0
1930 | 17
1930 | 0
1930 | 0
1930 | 0
1930 | 0
1947 | 17

**Comment by SuperFunks** [comment] 2020-09-12 07:45
I'm going to perform all the same compiling and testing from scratch on a different freshly installed distribution in AWS - just to rule out if have some bad settings going in my old on-premise Debian.

**Comment by SuperFunks** [comment] 2020-09-12 09:05
OK - So i went ahead and provisioned a SLES 15 in AWS - and from scratch compiled both CoreDNS 1.7, DNSTAP v0.2.1 on that host and redid the test:

6499 Queries Sent
888 Queries made it through DNSTAP v0.2.1 - which means on this SLES the results were even worse: ~73% event loss.

*I have updated by previous comments - as i realized my % calc was off :)*


**Resperf Results:**

![image](https://user-images.githubusercontent.com/20201219/92991904-0e22b600-f4e7-11ea-8620-d85991ddb51d.png)


**Terminals proving the setup:**

![image](https://user-images.githubusercontent.com/20201219/92991939-40341800-f4e7-11ea-96f6-4678284eaeac.png)

**Comment by SuperFunks** [comment] 2020-09-17 07:29
I dont know if its allowed to bump here - but bump :)

**Comment by cmikk** [comment] 2020-09-18 20:00
Bump heard.

I haven't been able to independently observe this slow down, but will take another look at your notes and try again.

**Comment by pforemski** [comment] 2020-09-18 22:47
Good news, we were able to reproduce this issue, thanks again for reporting this. We'll fix the bug as soon as possible, but please pardon the delay.

**Comment by cmikk** [comment] 2020-09-21 18:25
@SuperFunks  - please take a look at the blocking-mirror branch (at the linked pull request) and verify this fixes the issue for you.

**Comment by SuperFunks** [comment] 2020-09-24 12:09
Hey guys - i've been vacation :) - ill test with the pull request linked and verify the fix.
Thanks alot for looking into this!

**Comment by SuperFunks** [comment] 2020-09-24 13:19
Hi guys - so i compiled from the blocking-mirror branch - and this was the test results using:

resperf-->coredns(dnstap)-->dnstap-binary(golang)

**100** queries per second over 60 seconds (**0 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
6499 queries sent
6499 queries completed
6499 queries received

**500** queries per second over 60 seconds (**0 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
32499 queries sent
32499 queries completed
32499 queries received

**1000** queries per second over 60 seconds (**0 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
64999 queries sent
64999 queries completed
64999 queries received

**2000** queries per second over 60 seconds (**0 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
129999 queries sent
129999 queries completed
129999 queries received

**4000** queries per second over 60 seconds (**0 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
259999 queries sent
259999 queries completed
259999 queries received

**6500** queries per second over 60 seconds (**0 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
422499 queries sent
422499 queries completed
422499 queries received

**NOTE: Beyond this point the CoreDNS/DNSTAP Plugin is unable to keep up with resperf (8 vCPU VM) - so the result will show a drop-off in completed queries - but the ones that DO complete - we still want to see a DNSTAP event for.**

**7000** queries per second over 60 seconds (**110 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
454999 queries sent
454889 queries completed
454889 queries received

**8000** queries per second over 60 seconds (**356 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
519999 queries sent
519643 queries completed
519643 queries received

**10000** queries per second over 60 seconds (**1675 lost in CoreDNS/DNSTAP Plugin / 0 lost to DNSTAP Binary**):
649999 queries sent
648324 queries completed
648324 queries received

So all in all a fantastic result :) - It indeed seem to have fixed the issue. - I'm a bit sad i didnt try out this version sooner - so we could have caught this earlier. - By the looks of it this has been an issue for 1 year, 4 months, 3 days - but whos counting :)

Thanks again guys for the quick response and fix.

**Comment by cmikk** [comment] 2020-09-25 21:35
Thank you for confirming the fix.

The fix as it stands has the unfortunate side effect of causing one slow output to block all others, preventing which was the reason for the offending non-blocking channel send. This mechanism seems to be be *highly* sensitive to the specifics of timing and scheduling, and the loss seems to be triggered by buffering in the dnstap export plugin. A more  robust non-blocking solution may be in order.

**Comment by cmikk** [comment] 2020-09-25 21:41
Reopened until PR is merged.

**Closed as completed** 2020-10-01 18:06 UTC
